include: package:very_good_analysis/analysis_options.3.0.1.yaml

analyzer:
  exclude:
    # Build
    - "build/**"
    # Generated code
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
